[workspace]
members = [
"crates/marpii",
"crates/marpii-commands",
"crates/marpii-descriptor",
"crates/marpii-rmg",
"crates/marpii-rmg-shared",
"crates/marpii-rmg-tasks/marpii-rmg-tasks",
"crates/marpii-rmg-tasks/marpii-rmg-task-shader",
"crates/marpii-rmg-tasks/marpii-rmg-task-shared",

"examples/hello_triangle",
"examples/rust_shader",
"examples/rmg_rendering",
"examples/shared",
"examples/egui",
#"examples/scheduler_dryrun"
]


[workspace.dependencies]
ash = "0.37.1"
ash-window = "0.12"
raw-window-handle = "0.5"
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", rev="86d6042204e4c0f9ab04120155636d714037fadc"}
spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu", rev="86d6042204e4c0f9ab04120155636d714037fadc"}
bytemuck = "1"
log = "0.4.15"
ahash = "0.8.2"
anyhow = "1.0.56"
thiserror = "1.0"
tinyvec = {version = "1.6.0", features = ["alloc"]}
simple_logger = "4"
oos = {git = "https://gitlab.com/tendsinmende/oos.git"}
