[workspace]
members = [
"crates/marpii",
#"crates/marpii-command-graph",
"crates/marpii-rmg",
"crates/marpii-commands",
"crates/marpii-descriptor",

"examples/hello_triangle",
#"examples/render_graph",
"examples/rust_shader",
"examples/shader_builder",
"examples/rmg_rendering",
#"examples/vertex_graphics_shader",
#"examples/gltf_loading"
]
