[workspace]
members = [
"crates/marpii",
"crates/marpii-rmg",
"crates/marpii-rmg-shared",
"crates/marpii-commands",
"crates/marpii-descriptor",

"examples/hello_triangle",
"examples/rust_shader",
"examples/shader_builder",
"examples/rmg_rendering",
"examples/shared",
"examples/rmg_shader"
]
