[package]
name = "marpii-rmg-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
marpii = {path = "../marpii"}
