[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
marpii-rmg-shared = {path = "../../crates/marpii-rmg-shared"}
spirv-std = { workspace=true}
bytemuck.workspace = true
