[package]
name = "rmg_rendering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = "2.1.0"
anyhow = "1.0.56"

marpii = {path = "../../crates/marpii", features=["logging"]}
marpii-rmg = {path = "../../crates/marpii-rmg"}
marpii-descriptor = {path = "../../crates/marpii-descriptor"}
winit = "0.27"
log = "*"
image = "0.24.3"
glam = "0.21.3"
easy-gltf = "0.1.5"
shared = {path = "../shared"}
