[package]
name = "marpii-rmg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["logging"]
# if enabled, uses the log crate for messages.
logging = ["log"]

#if enabled the reasoning for pipeline barriers and queue syncs is printed into the TRACING
# level of log
log_reasoning = ["log"]


[dependencies]
anyhow = "1.0.56"
thiserror = "1.0"
slotmap = "1.0"
fxhash = "0.2.1"

marpii = {path = "../../crates/marpii"}
marpii-commands = {path = "../../crates/marpii-commands"}
marpii-descriptor = {path = "../../crates/marpii-descriptor"}
winit = "0.26.1"

log = {version = "0.4.15", optional = true}
