[package]
name = "marpii-rmg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["logging"]
# if enabled, uses the log crate for messages. Note that the graph prints reasoning of decissions into the tracing level
logging = ["log"]

# if enabled, enables rmg to bind and build acceleration structures.
ray-tracing = []


[dependencies]
anyhow = "1.0.56"
thiserror = "1.0"
slotmap = "1.0"
fxhash = "0.2.1"
ahash.workspace = true
tinyvec = {version = "1.6.0", features = ["alloc"]}
marpii = {path = "../../crates/marpii"}
marpii-commands = {path = "../../crates/marpii-commands"}
marpii-descriptor = {path = "../../crates/marpii-descriptor"}
marpii-rmg-shared = {path = "../../crates/marpii-rmg-shared", features = ["std"]}
winit = "0.27"

log = {workspace = true, optional = true}

#for the garbage collector
crossbeam-channel = "0.5.6"
#to spawn garbage collection
poll-promise = "0.1.0"
